// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncSyntax.Data;

#nullable disable

namespace SyncSyntax.Migrations
{
    [DbContext(typeof(ApDbContext))]
    [Migration("20260202112953_seedingInitaldata")]
    partial class seedingInitaldata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SyncSyntax.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lifestyle"
                        });
                });

            modelBuilder.Entity("SyncSyntax.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SyncSyntax.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FutureImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jane Doe",
                            CategoryId = 1,
                            Content = "Artificial Intelligence (AI) continues to evolve at a rapid pace, influencing various sectors from healthcare to finance. In 2024, we can expect significant advancements in machine learning algorithms, natural language processing, and AI ethics. Businesses are increasingly adopting AI-driven solutions to enhance customer experiences and streamline operations. Additionally, the integration of AI with other emerging technologies like blockchain and IoT will open new avenues for innovation.",
                            FutureImageURL = "https://example.com/images/ai-future.jpg",
                            PublishedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Future of AI: Trends to Watch in 2024"
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Smith",
                            CategoryId = 2,
                            Content = "In today's fast-paced digital world, maintaining mental health is more important than ever. Here are ten tips to help you stay balanced: 1) Set boundaries for screen time, 2) Practice mindfulness and meditation, 3) Stay connected with loved ones, 4) Engage in regular physical activity, 5) Prioritize sleep, 6) Limit exposure to negative news, 7) Seek professional help when needed, 8) Cultivate hobbies outside of technology, 9) Practice gratitude daily, and 10) Take regular breaks from social media.",
                            FutureImageURL = "https://example.com/images/mental-health-tips.jpg",
                            PublishedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "10 Tips for Maintaining Mental Health in a Digital World"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Emily Green",
                            CategoryId = 3,
                            Content = "Sustainable living is essential for preserving our planet for future generations. To reduce your carbon footprint, consider the following steps: 1) Use energy-efficient appliances, 2) Reduce, reuse, and recycle materials, 3) Opt for public transportation or carpooling, 4) Support local and organic food sources, 5) Minimize water usage, 6) Plant trees and maintain green spaces, 7) Choose renewable energy options when possible, and 8) Educate others about the importance of sustainability.",
                            FutureImageURL = "https://example.com/images/sustainable-living.jpg",
                            PublishedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sustainable Living: How to Reduce Your Carbon Footprint"
                        });
                });

            modelBuilder.Entity("SyncSyntax.Models.Comments", b =>
                {
                    b.HasOne("SyncSyntax.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SyncSyntax.Models.Post", b =>
                {
                    b.HasOne("SyncSyntax.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SyncSyntax.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SyncSyntax.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
